kata-containers/agent

protocols/client/client.go, protocols/client/client_test.go, protocols/mockserver/mockserver.go
The client connect helper can be reused by both the shim and the runtime. The mock server can be used to test client side code without having to wait for the agent to be ready.
Please do not merge it yet. I want to rebase it after #9 is merged so that we get basic container and process tracking in the mock server.
=> add client connect helper and a mock server

Makefile
build: Add a Makefile
This commit adds a makefile in order to simplify the build commands.
Fixes #30
=> build: Add a Makefile

.gitignore, Makefile
Create the binary as "kata-agent" as "agent" is too generic.
=> build: Name the binary "kata-agent"

agent.go, grpc.go, network.go
Use more structured logging and don't use the printf-style log calls
unless actually needed.
=> logging: Use structured logging and simplest log calls

Makefile, VERSION, agent.go
Generate a version string containing version number and commit that the
agent logs in when initialising the logger.
=> build: Add version details to binary

agent.go, api.go, grpc.go, pause.go
agent: Add shared PID namespace support
We want to be able to share the same PID namespace across all
containers of a sandbox. This commit allows for such a thing by
starting a new process from a pause binary, into a new PID ns.
This way, the process is considered as init process inside this
namespace and the namespace will exist as long as this process
runs.
Fixes #20
=> agent: Add shared PID namespace support

pause.go, pause_test.go
Remove signal handlers from pause-bin to prevent it from being
killed by other members of the pid namespace, causing all processes
in the same pid namespace being killed.
The agent can always kill the pause-bin with SIGKILL from outside.
Signed-off-by: Peng Tao <bergwolf@gmail.com>
=> pause-bin: remove signal handlers

mount.go
The source is the fs tag, it's not an actual path.
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>
=> mount: Do not resolve storage source for 9pfs

.pullapprove.yml
We should expect more than one approval from one of our approvers list
in order to consider a pull request as mergeable.
Fixes #67
=> pullapprove: A pull request needs 2 approval to be merged

agent.go, api.go, grpc.go, reaper.go
agent: Implement subreaper support
This commit turns the agent into a subreaper, in order to reap all
the processes started from any container. This is the only way to
make sure we won't end up with some zombies processes in case we
have some child processes terminating before their own children.
Fixes #23
=> agent: Implement subreaper support

agent.go, grpc.go, protocols/grpc/agent.pb.go, protocols/grpc/agent.proto, protocols/grpc/health.pb.go, protocols/grpc/oci.pb.go, protocols/mockserver/mockserver.go, reaper.go
protocols: grpc: Rely on exec_id provided by the runtime
This commit radically changes the way the process IDs are generated.
Indeed, for simplicity, the process ID, called exec_id, will always
be provided by the runtime.
The shim needs to be started knowing which exec_id it actually
represents. By having this information from the runtime, we make
things simple since the runtime will provide this directly to the
shim, with no need to interact with the agent.
Also, this commit stores the exitCode channel from the caller, so
that we don't need to keep it into a specific map for too long. This
prevents from the issue of continuing to use a map with a specific
PID entry, while this PID could have been re-assigned by the kernel.
Fixes #82
Signed-off-by: Sebastien Boeuf …
=> protocols: grpc: Rely on exec_id provided by the runtime

agent.go
agent: Close appropriate file handler
This commit fixes a bug in the code of agent.go file. It closes the
appropriate file handlers after they have been properly tested.
Fixes #88
=> agent: Close appropriate file handler

agent_test.go, api.go, channel_test.go, config_test.go
test: Increase unit test coverage
This commit adds some unit tests to cover few functions from the
following files: agent.go, channel.go and config.go.
Fixes #86
=> test: Increase unit test coverage

grpc.go
There is no need to try to signal a container already stopped.
Only need to return nil in that case.
Fixes: #96
Signed-off-by: Malhar Vora <mlvora.2010@gmail.com>
=> grpc: Return nil from SignalProcess() if container already stopped

mount.go
* Set `absSource` properly.
* Create 9pfs target directories in the guest.
=> mount: Fixes for both 9pfs and virtio-blk/scsi

Gopkg.lock, agent.go, vendor/github.com/opencontainers/runc/libcontainer/nsenter/README.md, vendor/github.com/opencontainers/runc/libcontainer/nsenter/namespace.h, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsenter.go, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsenter_gccgo.go, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsenter_test.go, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsenter_unsupported.go, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
We need to import `nsenter` package to make `init` function to be able to spawn a
new container.
Fixes: #95 
Signed-off-by: Malhar Vora <mlvora.2010@gmail.com>
=> agent: Add missing nsenter import

grpc.go
In grpc onlineCPUMem(), it just online CPU. I think this is not appropriate. Add online Mem.
Fixes #109 
Signed-off-by: Ruidong Cao <caoruidong@huawei.com>
=> grpc: Fix not online Mem

protocols/client/client.go
grpc.WithTimeout deprecated. Replace it with DialContext and context.WithTimeout.
Fixes: #114
Signed-off-by: Ruidong Cao <caoruidong@huawei.com>
=> client: Replace grpc.WithTimeout

Dockerfile, Makefile
Changes to add ppc64le support.
1. Passing arch varaible as build arg to Dockerfile.
2. Changes Dockerfile to pull correct golang tar ball.
Signed-off-by: Basheer K <basheer@linux.vnet.ibm.com>
=> Changes to add ppc64le support.

agent.go
Every time our GRPC functions ReadStdout() or ReadStderr() were
called, the entire allocated buffer was returned. This is wrong
since we don't know the amount of bytes we will get on both stdout
and stderr. Instead, this patch returns the slice corresponding to
the real amount of bytes read from the process.
Fixes #123
Fixes https://github.com/kata-containers/runtime/issues/20
=> agent: Fix the amount of bytes transmitted to the shim

agent.go, grpc.go
Just as the same ability as hyperstart, so that kata-agent
can work as the agent of hyperd/runv.
fixes #116
Signed-off-by: Lai Jiangshan <jiangshanlai@gmail.com>
=> agent: enable it to be the init process

agent.go, reaper.go
Fixes https://github.com/kata-containers/agent/issues/134
Always call `initLogger` before use it, make sure logrus is initialized
correctly when call into `initAgentAsInit()` func.
Signed-off-by: Zhang Wei <zhangwei555@huawei.com>
=> log: init logrus always before use it

api.go, grpc.go, network.go, protocols/mockserver/mockserver.go
Remove unused variables and struct fields reported by the `structcheck`
and `unused` linters.
Fixes #136.
=> lint: Remove unused variables and struct fields

agent.go
So that the log is actually human readable when being redirected to
a file.
Fixes: #140
=> log: disable color

agent.go, grpc.go, network.go, network_test.go, protocols/grpc/agent.pb.go, protocols/grpc/agent.proto, protocols/grpc/health.pb.go, protocols/grpc/oci.pb.go, protocols/mockserver/mockserver.go
WIP changes for making the networking interface gRPC protocol declarative.
The number of messages for route and interface handling is reduced to
two with this patch: UpdateRoutes and UpdateInterfaces.
UpdateInterfaces operates on an array of network-interfaces.  Doing this
allows for removal of interfaces by sending a new update request with
the interface no longer included.  For example, initially
UpdateInterfaces is called for 'A,' 'B' and 'C.'  Later a network remove of
network interface 'B' is carried out by calling UpdateInterfaces with
just 'A' and 'C'.  While this simplifies the protocol and runtime handling, it does put a
burden on the agent to write out the (non-necessarily changed) interface
details for 'A' and 'C' and determine that 'B' was removed.  In the event that network …
=> grpc: initial changes for networking protocol

agent.go, agent_test.go
A container being in stopped state is not a valid reason for not
accepting a call to getProcess(). Indeed, the explanation behind
this is that we want to make sure a shim can connect after the
process has already terminated. Some processes have a very short
lifetime and the shim might end up calling into WaitProcess()
after that. This does not mean that we cannot retrieve the output
and the exit code, they are waiting for the shim for that. But we
need to let the shim by not returning an error in this case.
Fixes #145
=> agent: Allow to retrieve the process of a stopped container

.ci/run.sh, .ci/setup.sh
.ci/setup.sh will setup the environment with
latest changes to be able to execute Kata Containers.
.ci/run.sh will execute the integration tests that live
in the 'kata-containers/tests' repository.
Fixes #152.
Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>
=> CI: add setup.sh and run.sh to execute integration tests

agent.go
Add a `source=` log field for parity with the other system components.
Fixes #157.
=> logging: Add source log field

agent.go, channel.go, config.go, grpc.go, mount.go, network.go, pkg/uevent/uevent.go, protocols/client/client.go, protocols/grpc/utils.go, reaper.go
grpcStatus implements errors returned by gRPC.  These errors are
serialized and transmitted on the wire between server and client, and allow
for additional data to be transmitted via the Details field in the status
proto.  gRPC service handlers should return an error created by this
package, and gRPC clients should expect a corresponding error to be
returned from the RPC call.
=> change most fmt.Errorf to "google.golang.org/grpc/status"

device.go
Use the functions provided in "golang.org/x/sys/unix" package
to get device major and minor numbers. These provide an accurate
architecture dependent implementation.
=> device: Use standard functions to get device Major and Minor

agent.go
Enable a full stacktrace display on internal error as an aid to
debugging.
Fixes #160.
=> main: Display full stacktrace on internal error

config.go, device.go, network_test.go, reaper.go
Fix issues identified by `varcheck` and `unconvert` linters.
=> Fix lint errors

agent_test.go, mount_test.go, network_test.go, pause_test.go
The unit tests in this repository are ultimately run by the
`go-test.sh` script in the `tests` repository. This script actually runs
the unit-tests *twice* **if** it is invoked as a non-`root` user: once
as the non-`root` user and once as `root`. This is done to cover all
possible scenarios: certain tests require super-user privileges whilst
other tests are only valid when running as a non-privileged user. The
script then combines the test results to calculate a coverage
percentage.
The Travis test runs are currently failing (in the first non-`root`
"run") as some of the tests require root privileges.
Make extra calls to `skipUnlessRoot()` for those failing tests to allow
them to be skipped when run as a non-`root` user and then run as `root`
in the second "run".
Fixes #177. …
=> Skip more tests if not root

.pullapprove.yml
A change to any of the gRPC protocol buffer files (`*.proto`) should
require an additional approval due to the potential impact it could
have across the system.
Fixes #175.
=> CI: Require pullapprove ack for protocol changes

mount.go, mount_test.go
Validate mount parameters where possible and log all parameters to help
debug scenarios where the client gRPC protocol is out-of-sync with the
agents (master) version.
Added a new test for `mount()`.
Fixes #170.
=> mount: Log params and validate

device.go, device_test.go
The statement returning an error in case VmPath is empty is wrong
because an Id can be provided instead. This patch fixes this behavior
and generates an error only if VmPath and Id are both empty.
Fixes #191
=> device: VmPath can be empty if an Id is provided

mount.go
The function mount() performs a generic mount and calls into
mount(2). The current error message is misleading as it refers
to an error in bind-mounting.
=> mount: Correct error message with mount failure.

Gopkg.lock, Gopkg.toml, vendor/github.com/opencontainers/runc/libcontainer/capabilities_linux.go, vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/apply_raw.go, vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go, vendor/github.com/opencontainers/runc/libcontainer/configs/validate/rootless.go, vendor/github.com/opencontainers/runc/libcontainer/container_linux.go, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c, vendor/github.com/opencontainers/runc/libcontainer/process_linux.go, vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux.go, vendor/github.com/opencontainers/runc/libcontainer/specconv/example.go, vendor/github.com/opencontainers/runc/libcontainer/specconv/spec_linux.go, vendor/github.com/opencontainers/runc/libcontainer/standard_init_linux.go, vendor/github.com/opencontainers/runc/libcontainer/state_linux.go, vendor/github.com/opencontainers/runc/libcontainer/user/lookup.go, vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unix.go, vendor/github.com/opencontainers/runc/libcontainer/user/lookup_windows.go, vendor/github.com/opencontainers/runc/libcontainer/user/user.go
Main reason for updating this vendoring is to include the recent
patch solving the container state issue when exec'ing a process
on a container not yet running.
Shortlog:
985628d libcontainer: Don't set container state to running when exec'ing
58415b4 Fix error message
4f4af7b rootless: set sticky bit if using XDG_RUNTIME_DIR
74e961e tests: allow to load kernel modules from a test container
43aea05 Label the masked tmpfs with the mount label
04e95b5 Add timeout while waiting for StartTransinetUnit completion signal from dbus
3d26fc3 cgroups/fs: fix NPE on Destroy than no cgroups are set
e7e303a Minor wording enhancement in readme
bf74951 libcontainer/user: platform dependent calls
8d7b573 makefile: make "release" PHONY
10a4cde Fix make shell
442a6cf VERSION: back to development
4fc53a8 …
=> vendor: Update libcontainer vendoring

network.go
The go netlink package has added more netlink socket protocols
than we need. Specify one to avoid failure due to unsupported
protocols.
Fixes: #209
=> network: specify netlink protocol

pkg/uevent/uevent.go
unix.SockaddrNetlink represents a netlink client with the Pid
being the netlink socket address. This can be assigned the actual
pid of the process, but in case we have two netlink sockets opened
at the same time, this results in errors in binding to the netlink
socket. Assign this to zero which means the kernel takes care of
assigning it.
See http://man7.org/linux/man-pages/man7/netlink.7.html
Fixes #216
=> uevent: Fix netlink error while assigning pid in netlink client

agent.go, agent_test.go, config.go, config_test.go
When agent_log is set to `debug` level, trace all grpc requests and
responses.
Fixes: #183
=> agent: add server interceptor to log grpc requests

grpc.go, network.go
This PR addresses the issues related to the way the agent currently tears down the network.
First it fixes an issue due to a modification of a list containing pointers instead of copies, while at the same time, this list is being parsed.
Then, with the idea of simplifying the way the network is removed, it introduces a commit removing the network removal code that was called when the sandbox was destroyed. Indeed, such a case means the VM is going to be shut down, leading to the removal of the network by the VM anyway.
Fixes #226
Fixes #230
=> agent: Simplify tearing down the network

agent.go, device.go, device_test.go, grpc.go, mount.go, mount_test.go, pkg/uevent/uevent.go
This PR gets rid of the device name prediction needed on the host side for block devices. This can be used for device handler that we add in the future including VFIO.
Fixes #198
=> Use PCI Addresses to determine the device names for virtio-blk devices

grpc.go, grpc_test.go, mockcontainer.go, mockcontainer_test.go, protocols/grpc/agent.pb.go, protocols/grpc/agent.proto, protocols/mockserver/mockserver.go
Add `StatsContainer` API to display container events
Fixes: #221
Signed-off-by: c00416947 <caihaomin@huawei.com>
=> grpc :Add the StatsContainer api for `events cli`

grpc.go, grpc_test.go
handleError function must log the errors when wait is false.
fixes #237
=> grpc: log errors in async commands

agent.go, config.go, config_test.go, signals.go, signals_test.go
signal: Switch to standard signal handling     
Change from using the golang "debug" package for providing backtraces to                       
using the Kata Project standard signal handling code:                                          
- A trace is written to the agents logger if a fatal signal is received                        
or an internal error is detected.              
- For consistency with other components, it is possible to enable a                            
coredump on fatal error. However, this is not desirable even with debug                        
enabled so the agent will only attempt to dump core if the new developer                       
mode (enabled by specifying `agent.devmode` on the guest kernel                                
command-line) is enabled. …
=> rework signal handling code and backtrace on SIGUSR1

grpc.go, grpc_test.go, mockcontainer.go
Once all vCPUs have been connected, cpuset cgroup MUST BE updated,
to achieve that, each cpuset cgroup parent of the container
MUST BE updated with the actual range of vCPUs.
fixes #239
=> grpc: honour CPU constraints in Kubernetes

agent.go, grpc.go, grpc_test.go, namespace.go, namespace_test.go
All containers in a pod need to share UTS and IPC
namespaces. Create these as persistent namespaces by bind-mounting
them to a persistent path and make all containers join these.
Fixes #248
=> namespaces: Create persistent UTS and IPC namespaces

agent.go, agent_test.go
Get cgroup mounts info from /proc/cgroups, this can get accurate cgroup subsystem info, if kernel don't surport to mount "/sys/fs/cgroup/cpu,cpuacct", agent should mount cpu and cpuacct subsystem separately.
Fix https://github.com/kata-containers/agent/issues/250
Signed-off-by: Shukui Yang <yangshukui@huawei.com>
=> Get cgroup mounts info from /proc/cgroups

grpc.go
Allow frozen containers receive signals in order to avoid runtime
waits for shim to finish.
fixes #252
=> grpc: signal frozen containers

device.go, mount.go, mount_test.go
Ephemeral volumes needs to mounted inside VM
and not passed as 9pfs mounts.
Signed-off-by: Harshal Patil <harshal.patil@in.ibm.com>
=> agent: Add support for ephemeral volumes

agent.go, network.go
When the agent is running as PID 1 it needs to setup the localhost
network interface. If not done, not only will "lo" not be available, but
the netlink library will cause the agent to segfault as it implicitly
assumes `lo` is "up".
Also added in extra parameter validation and error handling improvements.
Fixes #265.
=> network: Setup localhost when running as init

agent.go
Don't create the mount destination in `generalMount()` as that is
handled by `mountToRootfs()`.
Fixes #267.
=> mount: Remove redundant mkdir

agent.go, grpc.go
When agent runs as init process cgroup fs is mounted at /proc,
OnlineCPUMem must be able to support both paths, /proc and /sys/fs.
fixes #262
=> agent: honour CPU constraints when agent is the init process

.ci/lib.sh
Now static-checks.sh needs to have the
repository name as argument.
Fixes #274.
Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>
=> CI: update static-checks.sh in .ci/lib.sh

namespace.go
Using random char generation at early boot may slow the process due to
low entropy.
Also from kernel 4.14.36 rand call hangs due to low-entropy. Lets
remove dependency on rand at early sandbox creation.
Fixes: #278
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>
=> namespace: do not create path using rand.

agent.go, grpc.go
CloseStdin() is supposed to close only the standard input, which
helps the process to terminate in some cases. But for the case where
we are using a terminal, it should be closed by the agent once the
WaitProcess() will complete. Otherwise, closing it before the end of
the process could prevent some output from the terminal to reach the
shim.
Fixes #283
=> grpc: Don't close the terminal on CloseStdin() call

channel.go
Capture yamux messages to the logger.
Fixes #288.
=> logging: Redirect yamux warnings/errors to logger

protocols/client/client.go
We don't know how much time a sandbox can be paused,
hence connection write timeout should be disabled to
don't close the connection while the sandbox is paused.
The same issue has been fixed in kata-proxy, for katabuiltin proxy,
it also needs this fix.
fixes #294
Signed-off-by: fupan <lifupan@gmail.com>
=> agent: disable yamux keep alive

agent.go, grpc.go, grpc_test.go
Now cgroups are mounted at /sys/fs/cgroup, in the past
when initrd was used cgroups were mounted at /proc/cgroups
fixes #282
=> agent: Fix CPU tests for both initrd and rootfs image

agent.go
If any errors happens at that time, we should just tear down the
connection and start over again.
=> agent: do not quit on grpc serve errors

channel.go
yamux client runs in the proxy side, sometimes the client is handling
other requests and it's not able to response to the ping sent by the
server and the communication is closed. To avoid IO timeouts in the
communication between agent and proxy, keep alive should be disabled.
fixes kata-containers/proxy#70
fixes #231
=> yamux: disable yamux keep alive in server channel

agent.go
Memory cgroup requires setting use_hierarchy to 1 on the root.
fixes #318
=> agent: enable memory hierarchical account

protocols/client/client.go
This would bypass the grpc dialer backoff strategy and handle dial timeout
internally. Because we do not have a large number of concurrent
dialers, it is not reasonable to have such aggressive backoffs which
would kill kata containers boot up speed. For more information, see
https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md
Fixes: #320
This would speed up kata containers creation by about 0.5 second for non vm templating case and by about 1 second when vm templating is enabled.
=> client: bypass grpc dialer backoff strategy

protocols/client/client.go
Run containers that use vsock as communication channel inside VMs
(nested environments) randomly fails with following error:
```
Stderr: docker: Error response from daemon: OCI runtime create failed:
Failed to check if grpc server is working: context deadline exceeded: unknown.
```
Sometimes the connection with the container's vsock is slow because of
kata-runtime disables modern (don't rely on fast MMIO) on some devices
including vsocks. This issue can be fixed by increasing the dial timeout.
fixes #324
=> protocols: increase dial timeout

Gopkg.lock, protocols/client/client.go, protocols/client/client_test.go, vendor/github.com/grpc-ecosystem/grpc-opentracing/LICENSE, vendor/github.com/grpc-ecosystem/grpc-opentracing/PATENTS, vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/client.go, vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/errors.go, vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/options.go, vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/package.go, vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go, vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/shared.go, vendor/github.com/opentracing/opentracing-go/LICENSE, vendor/github.com/opentracing/opentracing-go/ext/tags.go, vendor/github.com/opentracing/opentracing-go/globaltracer.go, vendor/github.com/opentracing/opentracing-go/gocontext.go, vendor/github.com/opentracing/opentracing-go/log/field.go, vendor/github.com/opentracing/opentracing-go/log/util.go, vendor/github.com/opentracing/opentracing-go/noop.go, vendor/github.com/opentracing/opentracing-go/propagation.go, vendor/github.com/opentracing/opentracing-go/span.go, vendor/github.com/opentracing/opentracing-go/tracer.go
Add a `context.Context` parameter to the client `NewAgentClient()` API and
enable gRPC tracing if the specified context contains an opentracing
span.
Fixes #327.
=> client: Add context parameter and enable tracing support

Gopkg.lock, Gopkg.toml, channel.go, channel_test.go, protocols/client/client.go, vendor/github.com/hashicorp/yamux/session.go, vendor/github.com/hashicorp/yamux/stream.go, vendor/github.com/hashicorp/yamux/util.go
For both yamux client and server, we should wait on session close to get a clean state after close. Otherwise there might be inflight requests dirtying the serial channel and cause reconnection failures.
Fixes: #337
=> wait on yamux session close

agent.go, protocols/client/client.go
Smaller set -- pulled each of the commits from 1.2.0 to HEAD (cd8f37b).  
Analysis:
1.2.1 | * 93fe84e protocols: increase dial timeout
NO:  | * 730b977 client: bypass grpc dialer backoff strategy
1.2.1  | * 41c09c2 agent: enable memory hierarchical account
NO    | * 4f70b1c channel: remove unused functions
NO:   | * f6486e7 channel: support communication channel hotplug
=> Stable 1.2.1 candidate

device.go, device_test.go
Host device's major-minor numbers are mapped to guest major-minor numbers,
for example in the host the major-minor number for /dev/loop0p1 is 259:1,
when it's attached to the VM now the major-minor number is 8:0, these
conversion must be reflected in devices and resources lists, the first list
is used to mount the device in the container and the second one is to update
the devices cgroup.
fixes #351
=> agent: update resources list with the right device major-minor number

channel.go, channel_test.go
So that if serial yamux session fails to close somehow,
we can catch it.
Fixes: #359
=> channel: add serial yamux channel close timeout

.ci/run.sh, Makefile
Allow make proto to work under the CI. So later we are able to check
pb.go files in CI.
fixes #340
Signed-off-by: Ruidong Cao <caoruidong@huawei.com>
=> CI: Add "make proto"

Makefile
Inorder to get runc/libcontainer/seccomp/seccomp_linux.go
built in, build agent with seccomp tag.
Fixes: #104
Signed-off-by: Nitesh Konkar niteshkonkar@in.ibm.com
=> Makefile: Build agent with tag seccomp to support seccomp

device.go, pkg/uevent/uevent.go
When testing network hotplug, I see some uevent listener related errors:
1. panic on closing the notification channels
2. device might appear before we listen to the uevents
3. panic on returning negative count in Read method to bufio
Note that even with this PR, network hotplug is still not working for me.
/cc @devimc @caoruidong @sboeuf
=> fix uevent related errors

Gopkg.lock, Gopkg.toml, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go, vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
Fixes #373
Bump runtime-spec version to "5806c35637336642129d03657419829569abc5aa"
Change logs:
5d9aa69 config-linux: Add Intel RDT/MBA Linux support
6f5fcd4 Support for network namespace in windows
06cf899 config-linux: add Intel RDT CLOS name sharing support
f3be7d2 config: clarify source mount
65fac2b Fix camelCasing on idType to align with other Windows spec conventions
da8adc9 incorporating edits from JTerry's feedback
c182ebc meeting: Bump July meeting from the 4th to the 11th
e01b694 config: Add Windows Devices to Schema
81d81f3 docs: Added kata-runtime to implementations
b0700ad Add gVisor to the implementations list
9e459a6 .travis.yml: Get schema dependencies in before_install
692abcb .travis: Bump minimum Go version to 1.9
fd39559 config: Clarify execution environment for hooks …
=> vendor: bump runtime-spec version

agent.go
We should not receive many hotplug uevents. Log these so we can
track what devices have been attached in the logs.
=> uevent: Add logs for uevents

agent.go, epoll.go, epoll_test.go, grpc.go, mockreaper.go, reaper.go
Kata assumes once a process exits, it's IO will also
close automatically, thus the client will wait on the
process's IO closed and then do some cleanup for this
process. But the issue is that if the process forked
some background children processes running as daemon
process, thus those children process will intherit its
parent terminal, and even its parent exited, its terminal
will not close as the children running.
So this commit will try to fix this issue by detecting
the process's exit and then notify the client that the
process has exited and there's no need to wait on its IO.
Fixes: #370
Signed-off-by: fupan <lifupan@gmail.com>
=> agent: fix the issue of missing close process terminal

device.go, device_test.go, grpc.go
1. rescan pci bus before waiting for a new device
2. fix redefined notify channel when waiting for a new device
Fixes: #372
I made this depends on #375 since they both modify the same function and would naturally conflict.
=> fix up remaining issues with pci hotplug and uevent listening

agent.go
Don't fail if `dev` is already mounted
fixes #264
cc @jodh-intel @bergwolf 
=> agent: support agent as init process in rootfs images

agent.go, device.go, device_test.go, grpc.go, pkg/uevent/uevent.go
The PR back ports recent uevent related fixes to stable 1.2 branch, including following commits:
a628496 -         [Peng Tao]      device: rescan pci bus before waiting for new devices
1310f3d -         [Peng Tao]      device: fix redefined notify channel
ef62167 -         [Archana Shinde]        uevent: Add logs for uevents
2b89a0a -        [Peng Tao]      uevent: fix crash on read errors
3441244 -        [Peng Tao]      device: do not close notify channel when wait timeout
=> Uevent fix for stable 1.2

agent.go, device.go, device_test.go, grpc.go, pkg/uevent/uevent.go
The PR back ports recent uevent related fixes to stable 1.1 branch, including following commits:
a628496 - [Peng Tao] device: rescan pci bus before waiting for new devices
1310f3d - [Peng Tao] device: fix redefined notify channel
ef62167 - [Archana Shinde] uevent: Add logs for uevents
2b89a0a - [Peng Tao] uevent: fix crash on read errors
3441244 - [Peng Tao] device: do not close notify channel when wait timeout
=> Uevent fix for stable 1.1

agent.go, device.go
When memory is hot added the udevpath is:
uevent-devpath=/devices/system/memory/memory81
But when the agent checks for the path it expects it  checks
in the /sys filesystem.
Fixes: #388
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>
=> memory: Fix update memory path.

protocols/client/client.go
Since the Yamux's keepalive has been disabled both
on the server and the client side, and this brings
a weird issue where the communication between the
proxy and the agent hangs. The same issue has been
fixed in kata proxy by:
"https://github.com/kata-containers/proxy/pull/91".
This commit just cherry-pick that patch here to
fix the same issue on kata builtin proxy.
Fixes: #396
Signed-off-by: fupan <lifupan@gmail.com>
=> agent: Fix the issue of stdout hang on builtin proxy

Makefile
Build the agent binary as Position-Independent-Executable (PIE) for improved
security and compliancy with distros packaging guidelines.
Fixes: #408
=> agent: build as Position-Independent-Executable

Makefile
Agent would be built by seccomp tag if SECCOMP is set to
yes. Else it shall be set to no.
Fixes: #420
Signed-off-by: Nitesh Konkar niteshkonkar@in.ibm.com
=> Makefile: Decide if agent will be built by seccomp tag

protocols/client/client_test.go
Remove `/tmp/agentserver.socker` when test case is done and output firendly error message when remove the file failed.
Fixes #418
Signed-off-by: NingBo <ning.bo9@zte.com.cn>
=> client: do cleanup after UT stop mock server

grpc.go, grpc_test.go
specconv.CreateLibcontainerConfig returns a configuration without rlimits,
because it can't convert posixRlimits to Rlimits.
Convert posixRlimits to Rlimits and set rlimits in libcontainer configuration
before finishing container creation.
fixes #430
fixes github.com/kata-containers/runtime#913
=> grpc:  support rlimits

device.go
Support the block storage driver "nvdimm".
Signed-off-by: Hui Zhu <teawater@hyper.sh>
=> block: add support of block storage driver "nvdimm"

grpc.go
Use /run/libcontainer as root path for container factory, as /tmp may
be read only for some configuration / architectures.
Fixes: #435
Signed-off-by: Marco Vedovati <mvedovati@suse.com>
=> libcontainer: use /run as root containers path

device.go, mount.go
Add support for discovery of rootfs passed in via virtio-mmio.
The discovery is done based on predicted device name.
Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>
=> virtio-mmio: Add support for virtio-mmio blk devices

CODEOWNERS
If a proto file is changed then we want a larger number of folks
to know about and review it. Add them to the CODEOWNERS file.
Fixes: #460
Signed-off-by: Graham Whaley <graham.whaley@intel.com>
=> CODEOWNERS: add group review trigger for proto file changes

grpc.go, grpc_test.go
We support most of the namespaced sysctls today as we pass them to
libcontainer as part of the OCI spec. libcontainer then applies them
for the container after veryfing they can be applied.
However, the verification fails for network related sysctls as
libcontainer expects a separate network namespace for network
sysctls. This check fails for us as we create network namspace on
the host side. To fix these, apply the network sysctls manually
and purge them from the spec, leaving other sysctls to be applied
by libcontainer.
Fixes 472
=> sysctl: Add complete sysctl support

grpc.go, grpc_test.go
cpu hotplug tests fail randomly in nested environments because 1 second is
not enough for the kernel and qemu to allocate and connect the vcpus.
fixes #474
=> agent: increase the number of tries to online vcpus

tracing.go
Don't log trace-related messages unless tracing is actually enabled. If tracing is not enabled, trace spans are still created, but the tracer is a NOP. However, this is an implementation detail the user does not need
to be aware of so hide trace logs unless the user has enabled tracing explicitly.
Fixes #482.
=> tracing: Hide trace messages unless tracing enabled

TRACING.md
Simplify agent tracing terminology by renaming "trace type" to "trace mode". This allows what was called "trace sub-type" to be called "trace type".
Also, remove the example showing how to set the trace mode in the runtime's configuration file. The reason for doing this being that the plan is for the runtime to control adding such guest kernel command line options as part of https://github.com/kata-containers/runtime/issues/1369.
Fixes #488.
=> Change tracing terms

agent.go
mount /run as a tmpfs to support read-only rootfs.
fixes #495
=> agent: support read-only rootfs

agent.go, channel.go, grpc.go, grpc_test.go, protocols/grpc/utils_test.go
gometalinter is deprecated and will be archived April '19. The
suggestion is to switch to golangci-lint which is apparently 5x faster
than gometalinter.
Partially fixes: github.com/kata-containers/runtime#1377
=> lint: Switch golang linter to golangci-lint

Makefile
Install the agent systemd targets after evaluating the systemd
unitdir configured for the systemd package.
We were initially assuming this as "/usr/lib/systemd/system/"
but this is not the case for all distros such as debian and ubuntu.
Fixes #498
=> make: Install systemd targets in systemd unit dir

kata-containers.target
Add chronyd service so that it is started with kata-containers.target.
Fixes #500
=> systemd-target: Add chronyd.service to kata-containers.target

agent.go, channel.go, config.go, config_test.go
With a recent kernel change, the agent can no longer rely on
/dev/vsock and AF_VSOCK in socket(), to detect if vhost-vsock
channel has been passed by the runtime.
These are not created when the vhost-vsock driver is initialised.
The runtime should now pass this information explicilty.
Based on the channel type passed, the agent now checks for that
partcular channel type.
In case it is not passed, check for both serial and vsock channel.
This also introduces a change in the way vsock channel is detected
by checking for devices under the vhost-vsock driver path.
Fixes #506
=> channel: Check for channel type in kernel cmdline options

agent.go
It should show servErr but not err.
Fixes: #511
Signed-off-by: Hui Zhu <teawater@hyper.sh>
=> agent: Fix "agent grpc server quits" show wrong error

.ci/lib.sh
If we are testing an stable branch, we need to checkout
to the correct branch on the tests repository.
Fixes: #516.
Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>
=> ci: travis: checkout test repo to correct branch

Gopkg.lock, Gopkg.toml, vendor/github.com/mdlayher/vsock/conn_linux.go, vendor/github.com/mdlayher/vsock/doc.go, vendor/github.com/mdlayher/vsock/fd_linux.go, vendor/github.com/mdlayher/vsock/fd_linux_gteq_1.12.go, vendor/github.com/mdlayher/vsock/fd_linux_lt_1.12.go, vendor/github.com/mdlayher/vsock/ioctl_linux.go, vendor/github.com/mdlayher/vsock/listener_linux.go, vendor/github.com/mdlayher/vsock/vsock.go, vendor/github.com/mdlayher/vsock/vsock_others.go
This version of vsock fully supports Go 1.12 runtime network poller
integration, and is compliant with net.Listener and net.Conn as
checked by golang.org/x/net/nettest.
Fixes #485.
Signed-off-by: Matt Layher <mdlayher@gmail.com>
=> vendor: use latest github.com/mdlayher/vsock

Makefile
Add build option STATIC=1 to statically link kata-agent.
Fixes: #522
Signed-off-by: Hui Zhu <teawater@hyper.sh>
=> make: Add build option STATIC=1 to statically link

grpc.go, grpc_test.go
If container initProcess doesn't install any handler for SIGTERM,
it will ignore this signal, thus send it SIGKILL instead of SIGTERM
to terminate it.
Fixes:#525
Signed-off-by: lifupan <lifupan@gmail.com>
=> agent: send SIGKILL instead of SIGTERM to container init process

device.go, mount.go, mount_test.go
Local storage is just a directory created inside the VM.
This will use whatever the storage driver is for the container
rootfs. This will normally be 9p, but in some cases could be
device mapper. In this case the directory will benefit from the improved
performance of device mapper.
Signed-off-by: Alex Price <aprice@atlassian.com>
=> agent: Add support for local storage

TRACING.md, kata-agent.service.in
Partially revert commit 272f273961e70096938ac7a3fe6477023c8f715a to stop a user-initiated shutdown (typing `exit` or control-d for example at a shall prompt) from hanging and leaving the hypervisor running.
Fixes #479.
=> service: Fix user initiated shutdown

TRACING.md
Fix a broken link in `TRACING.md`.
Fixes #539.
=> docs: Fix markdown in TRACING.md

config.go, config_test.go, grpc.go
Log the trace mode and type when tracing is enabled. The change makes it clearer that static tracing is enabled when the agent parsers the kernel command line (`config.go`) and dynamic tracing is enabled by gRPC (`grpc.go`).
Specifics of change:
- Rename variables to match the terms defined in `TRACING.md`.
- Pass trace mode and trace type arguments to `enableTracing()`.
- Change the tense of the message displayed by `enableTracing()` so that the message indicates that tracing *is* enabled, not *about to be*.
Fixes #504.
=> agent: Display trace details

README.md, agent.go, config.go
Start a debug console if the `agent.debug_console` option is part of the kernel
command line and a shell (bash or sh) is installed in the rootfs.
The debug console is useful when the developer wants to debug the agent process
or any other processes (even containers). The current way to do this is by
modifying a systemd target + creating a new system unit, the problem with this
approach is that it's not user-friendly and we depend on systemd, since it must
be installed in the rootfs.
fixes #546
=> agent: support debug console

Gopkg.lock, Gopkg.toml, vendor/github.com/mdlayher/vsock/doc.go, vendor/github.com/mdlayher/vsock/goversion_unsupported.go
The vsock package needs go >= 1.11. The latest version of the package adds a
compile time check on the go version.
Fixes: #542
Signed-off-by: Marco Vedovati <mvedovati@suse.com>
=> vendor: update vsock package version

device.go, device_amd64.go, device_arm64.go, device_ppc64le.go, device_s390x.go
For now, update interface in agent will fail when hot-add
nic to a running containers on arm64 as rescan pci bus will
occur between uf and bf of shpc hotplug interrupt handling.
Another problem is that the rootBusPath will be
"/devices/platform/4010000000.pcie/pci0000:00" on arm64.
To enable hot-add nic on arm64, rootBusPath should be changed here
and shpc hotplug should be disabled in guest kernel.
This patch just change rootBusPath.
Fixes: #544
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>
@bergwolf @jodh-intel @teawater @Pennyzct
=> updateInterface: enable hot-add nic on arm64

README.md
Add link in the README to the existing cpuset doc which previously was not very visible.
Fixes #557.
=> docs: Add missing document link

mount.go
We need a proper rollback to decrement the sandbox storage
reference counter when addStorages() failed.
Fixes: #549
Signed-off-by: Xie Yongji <xieyongji@baidu.com>
=> mount: Add a proper rollback path to addStorages()

README.md, documentation/features/cpuset.md
Fix spelling mistakes and formatting issues.
Fixes #562.
=> docs: Fix typos and formatting

kata-containers.target
Invoke tmp.mount by adding it to kata-containers.target.
This is not invoked by systemd with current rootfs setup we have
as one of the dependencies for tmp.mount is systemd-remount-fs.service
which depends on /etc/fstab file being present(it is currenty missing)
Instead of adding that file, start the tmp.mount unit by including
it in kata-containers.target
With this and change in os-builder to not delete the tmp.mount unit,
(https://github.com/kata-containers/osbuilder/pull/301) /tmp should now
be writeable for systemd based images.
For initrd this is handled by the agent itself.
Fixes #https://github.com/kata-containers/osbuilder/issues/300
=> tmp: Add tmp.mount to kata-containers.target

mount.go, mount_test.go
For block devices added by acrn, virtpath is directly udpated
in storage.source and so no scanning of PCIAddr is required.
This is because, the virtio-blk device is not hot-plugged but
added during VM launch and updated later with container rootfs
using block rescan feature.
Fixes: #573
Signed-off-by: Vijay Dhanraj <vijay.dhanraj@intel.com>
=> mount: Virtio-blk container rootfs mount for ACRN hypervisor

Gopkg.lock, Gopkg.toml, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
The latest commit introduces quite a few changes in the VM spec.
These are required by the runtime. Without this we cannot update the
vendoring in the runtime for the runtime-spec.
Fixes #597
=> vendor: Update the vendoring for github.com/opencontainers/runtime-spec

Gopkg.lock, Gopkg.toml, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
This is introduced as a transitive dependency for the runtime
and causes vendored pacakges to break as the change in the runtime-spec
introduces a backward incompatible change for dependent packages.
Fixes #597
=> vendor: Move to a previous version for runtime-spec vendor

agent.go
Fixes #609
Signed-off-by: leizhongkai <leizhongkai@huawei.com>
=> agent: delete element of sandbox.deviceWatchers with right key

Makefile, agent.go, mount.go, mount_test.go
Make NoPivotRoot depend on the actual FS type of `/` being rootfs,
instead of agent being the init process.
In this way, an initrd built without AGENT_INIT can still be used to run
containers.
Fixes: #611
=> agent: make NoPivotRoot config depend on `/` fs type

Gopkg.lock
`dep check` is being run by our CI to make sure that the dependency
files and vendor repositories are in sync. This PR brings them into sync
to pass checks.
Fixes: #617
Signed-off-by: Ganesh Maharaj Mahalingam <ganesh.mahalingam@intel.com>
=> vendor: dep check fixes

device.go, device_test.go, mount.go
Add support for CCW virtio blk. The virtio blk requires a special
handling to the PCI devices.
The divices information during the hotplug are updated in '/sys/devices/css0/',
and the disk name can be found under '/sys/bus/ccw/devices'
More detailed info at:https://public.dhe.ibm.com/software/dw/linux390/docu/lhs1vg00.pdf
Fixes: #599
Signed-off-by: Alice Frosi <afrosi@de.ibm.com>
=> s390x: add virtio-blk-ccw support

pause.go
gcc __attribute__ constructors cannot take arguments and cannot
access main function arguments on musl. Such functionality is glibc
specific and only works on x86 and x86_64. As a result, the pause
binary always quits on musl causing sandbox share pidns to malfunction.
=> agent: sandbox_pause should not take arguments

pause.go
When agent runs as init, it is not able to read `/proc/self/cmdline` because
of `/proc` has not been mounted when the C constructor is called.
This reverts commit cfbd8c921dea1c30532119127127e40428d5853f.
fixes #620
=> revert: agent: sandbox_pause should get arguments from proc

network.go, network_test.go
Routes with proto kernel are automatically added by the kernel
when an interface is added with ip assigned as a subnet address.
With github.com/kata-containers/runtime#1936, these routes will no
longer be sent from the runtime.
Depends-on: github.com/kata-containers/runtime#1936
Fixes: #623
=> network: While updating routes, do not delete routes with proto "kernel"

device_s390x.go
On s390x the right rootBusPath to hotplug ccw device is "/devices/css0"
Fixes: #631
Signed-off-by: Alice Frosi <afrosi@de.ibm.com>
=> s390s: fix rootBusPath

agent.go, device.go, device_test.go, mount.go, mount_test.go
There is an issue with the waitForDevice:
this wait will first check is the device's sys entry existed in /sys directory,
and if it existed, then it would return directly. How ever, the kernel register
a new device as an order of: 1) create the sys entry in /sys; 2) mknod in devtmpfs;
3) send uevent to userspace. The problem here is when the "wait" tested the sys entry
existed and return directly, but at that time the kernel would haven't created the device
node in devtmpfs, thus the following mount failed with couldn't resolve the device path.
Thus, the correct choice for waiting the device is depends on the uevent notice, since
once the kernel sended the device "add" uevent, it had created the device node in devtmpfs
yet.
Fixes: #628
Signed-off-by: lifupan <lifupan@gmail.com>
=> device: fix the issue of failed waiting on device appeared in /dev

mount.go, mount_test.go
This commit ensures that local directory storage types have the correct
permissions set on the mount point. We can't rely on os.MkdirAll to
set the desired permissions, as the agent process umask will determine
the permissions on the created directory. To fix this we call os.Chmod
on the mount point with the desired permissions.
Additional tests have been added.
Fixes #636
Signed-off-by: Alex Price <aprice@atlassian.com>
=> mount: ensure local directory storage types have the correct permissions

.ci/install_go.sh, .travis.yml, Gopkg.lock, Makefile, agent.go, agent_test.go, config_test.go, device.go, device_test.go, grpc.go, grpc_test.go, mount.go, mount_test.go
Summary of changes to add to the `stable-1.8` branch:
177d240 (originally 006fdfe) - `device: fix the issue of failed waiting on device appeared in /dev`
a64652a (originally 545a411) - `mount: ensure local directory storage types have the correct permissions`
0ec5e6c (originally b1a4284) - `travis: Fix golang version`
2a75586 (originally 4ab32a9) - `vendor: dep check fixes`
bbb7b11 (originally cf20c9b) - `ci: Allow travis to use go install script`
b725a88 (originally 5ffb2a6) - `agent: make NoPivotRoot config depend on `/` fs type`
79f51ae (originally a1c9d50) - `make: install depends on $(TARGET)`
60a20bf (originally 7c97a0a) - `agent: delete element of sandbox.deviceWatchers with right key`
b908072 (originally 4354b24) - `tests: Add lots of new unit tests`
bdf4ab0 (originally d4a22d1) - …
=> Backports for 1.8 stable branch

.travis.yml
Update the `.travis.yml` config file to call the common CI setup script.
This ensures Travis jobs have the correct set of packages installed for running all the static checks.
Fixes: #648.
=> CI: Make Travis call common setup

TRACING.md
fixed the "Guest journal redirector" part of TRACING.md error, from "vsock-to-udp-server.sh" to "vsock-to-text-server.sh"
=> Fix incorrect script reference in TRACING.md

protocols/client/client.go, protocols/client/client_test.go
hybrid vsocks is a new way to communicate host and guest,
currently it's only supported by firecracker.
fixes #642
=> protocols/client: support hybrid vsocks

protocols/client/client.go, protocols/client/client_test.go
For func NewAgentClient(), the parameter of 'enableYamux'
has nothing to do with 'Proxybuiltin' and it can be figured
out by the dialer's address scheme. Thus there is no need to
pass the parameter 'enableYamux'.
Fixes: #659
Signed-off-by: lifupan <lifupan@gmail.com>
=> client: remove the parameter of 'enableYamux'

protocols/client/client.go, protocols/client/client_test.go
This reverts commit 717ee24bdf0cf3be7390022abb6e2dee153f65f6.
Since most of the runtime unit tests depending on grpc + unix socket without yamux,
and that commit would break those tests, thus I have to revert this commit.
Fixes: #662
=> Revert "client: remove the parameter of 'enableYamux'"

network.go
make sure the parent directory exists when opening the resolv.conf
file.
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
=> network: ensure parent directories exist

agent.go, tracing.go
We should use an alias for opentracing.Span as this can be changed in the
future when we implement other tracing methods.
Fixes #664
Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>
=> tracing: Generate an alias for opentracing.Span

agent.go, channel.go, mount.go, network.go, tracing.go
This wrapper is for opentracing functions, once that we move to another tracer
this will help us to simplify the work by just modifying the name of the function
in a variable instead of renaming all of them in the different files.
Fixes #670
Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>
=> tracing: Wrapper for tracing functions

TRACING.md
This specifies where the services and the conf should be placed in
order to run the tracing on the agent.
Fixes #674
Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>
=> docs: Add missing steps at TRACING.md

TRACING.md
This adds the instruction of enabling the services and the installation of the
configuration file used for tracing.
Fixes #679
Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>
=> docs: Add enable services and installation steps for TRACING.md

agent.go, pause.go, pause_test.go
gcc __attribute__ constructors cannot take arguments and cannot
access main function arguments on musl. Such functionality is glibc
specific and only works on x86 and x86_64. As a result, the pause
binary always quits on musl causing sandbox share pidns to malfunction.
Let's use env to indicate pause instead.
Fixes: #584
Signed-off-by: Peng Tao <bergwolf@hyper.sh>
=> agent: fix pause bin on musl

README.md, agent.go, config.go, config_test.go
some hypervisors, like firecracker, don't have connected a unix socket to
`/dev/console` making impossible to start a debugging console.
Use vsock connection as standard input and output (std*) for the shell
process.
Add cmdline option to specify the vsock port to connect the debugging console.
fixes #666
=> agent: firecracker: support debugging console

README.md, agent.go, config.go, config_test.go, device.go, device_test.go
This adds an option to the agent to control the hotplug timeout of block devices.
Retains the previous behaviour of defaulting to 3 seconds if not specified.
Can be increased when block device hot plugging is taking longer than expected.
Fixes #683
Signed-off-by: Alex Price <aprice@atlassian.com>
=> config: add option to control hotplug timeout of block devices

protocols/client/client.go
Rust agent(grpc-rs) cannot work with firecacker because the first package
will be dropped or truncated by HybridVSockDialer read EOT code.
This issue was reported in
https://github.com/kata-containers/kata-containers/issues/79
Golang agent(grpc-golang) is also affected by this issue.  But it is first
package is 9 bytes FRAME_SETTINGS.  Drop it will not affect subsequent
communications.
This commit change to use recv peek that will do same check with read
EOT but not drop any package.
Fixes: #695
Signed-off-by: Hui Zhu <teawater@antfin.com>
=> client.go: HybridVSockDialer: Change Read EOT to recv peek

protocols/client/client.go
I found that unix.Recvfrom will not return err to io.EOF if it get
an EOF.  It just set return size n to 0.
That will make function commonDialer return. Grpc dialer will handle
it.
This commit add code to check return size n and set err to io.EOF if
n is 0.
Fixes: #697
Signed-off-by: Hui Zhu <teawater@antfin.com>
=> client.go: HybridVSockDialer: Check return size n of unix.Recvfrom

.ci/run.sh
run.sh might shutdown docker service and ci would fail when trying
to configure docker runtime.
=> ci: install docker before configure

protocols/client/client.go
kata runtime jenkins-ci-ubuntu-1804-firecracker always failed when agent
of vendor is updated to new version in
https://github.com/kata-containers/runtime/pull/2285.
This test passed after added code to close dup fd after receive packet
in http://jenkins.katacontainers.io/job/kata-containers-runtime-ubuntu-1804-PR-firecracker/1339/.
Fixes: #703
Signed-off-by: Hui Zhu <teawater@antfin.com>
=> client.go: HybridVSockDialer: Close dup fd after receive packet

network.go
make sure the parent directory exists when opening the resolv.conf
file.
fixes: #669
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
=> [backport 1.9] network: ensure parent directories exist

protocols/client/client.go
Revert changes as bring some instability to CI. After find the root cause it will be merged again.
Fixes: #716
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>
=> Revert: client.go: HybridVSockDialer: Change Read EOT to recv peek

network.go, network_test.go
Do not ignore ipv6 addresses and routes. These are not processes along
with ipv4 routes.
Add tests to verify ipv6 addresses and routes are processed
with `updateRoutes`.
Depends-on: github.com/kata-containers/runtime#2420
Fixes #721
=> ipv6: Add support for ipv6

protocols/client/client.go
**Which feature do you think can be improved?**
New Firecracker `v0.20.0` has changed the host-initiated vsock connection protocol to include a trivial handshake.
The new protocol looks like this:
```
- [host] CONNECT <port><LF>
- [guest/success] OK <assigned_host_port><LF>
```
See PR [firecracker-microvm/firecracker#1472](https://github.com/firecracker-microvm/firecracker/pull/1472) for detailed info.
=> FC: Add new vsock connection handshake

agent.go
close stdin to avoid agent be killed through the stdin
fixes #746
=> agent: don't receive signals from stdin

agent.go, device.go, device_amd64.go, device_arm64.go, device_ppc64le.go, device_s390x.go, mount.go, mount_test.go
Agent has to wait for pmem/nvdimm devices to appear in the guest.
The agent can use udev and the ACPI device path to identify when a pmem/nvdimm
device has been hotplugged in the guest.
For example when `/dev/pmem1` is hotplugged, the ACPI dev path may look like:
```
/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0012:00/ndbus0/region1/pfn1.1/block/pmem1
```
The udev routine catches the above path and return the full path to the device:
`/dev/pmem1`
fixes #753
cc @amshinde @lifupan @jodh-intel
=> agent: support pmem/nvdimm hotplug

README.md, agent.go, agent_test.go, config.go, config_test.go
Set `agent.unified_cgroup_hierarchy` to `1` or `true` to enable cgroups v2 in the guest.
Set `agent.unified_cgroup_hierarchy` to `0` or `false` to disable cgroups v2 in the guest.
By default cgroups v2 is disabled.
cc @fidencio @crobinso
=> Add kernel cmdline parameter to enable or disable cgroups v2

README.md, agent.go, config.go, config_test.go, grpc.go, grpc_test.go
Adds a cmdline option to configure the stdout/stderr pipe sizes.
Uses `F_SETPIPE_SZ` to resize the write side of the pipe after
creation.
Example Cmdline option: `agent.container_pipe_size=2097152`
fixes #755
Signed-off-by: Alex Price <aprice@atlassian.com>
=> agent: add configurable container pipe size cmdline option

agent.go
reason: If someone want to exec a process in the container, kata-agent will
create a epollfd to monitor the pts fd event. However epollfd is not closed
when exec process exit, which cause fd is left in the kata-agent process.
fixes: #762
Signed-off-by: jiangpengfei <jiangpengfei9@huawei.com>
=> agent: fix epoll fd left in the kata-agent when exec process

agent.go, signals.go
Don't close stdin, since it's used as the controlling terminal for the agent
when it's the init process, instead the signals from the keyboard must not be
fatal.
fixes #765
fixes github.com/kata-containers/tests#2405
=> agent: signal from keyboard must not be fatal

Makefile
This provide a flag "STRIP=yes" to strip the golang binary
After make STRIP=yes
24757576 kata-agent.nostrip*
19651136 kata-agent.striped*
It reduces the golang binary size ~5MB
Fixs: #739
Signed-off-by: Jia He <justin.he@arm.com>
=> build: Add support to strip the agent golang binary

mount.go, mount_test.go
virtio_fs was the name used for the module in the very early stages of
its development.
Resolves: #737
Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>
=> mount: Use "virtiofs" instead of "virtio_fs"

protocols/client/client_test.go
The way to parse URLs in Go 1.13 has changed, now the `url.Parse` validates
that the port is only decimals, so the content of the error message when a
invalid port is used will change from "Invalid vsock port" to "invalid port",
hence the expected error message in the unit tests must change.
For more information about the change in Golang 1.13 see:
https://github.com/golang/go/commit/61bb56ad63992a3199acc55b2537c8355ef887b6
fixes #772
=> protocols: fix client unit tests for go 1.13

channel.go
The epoll_wait syscall would be interrupted by signal,
thus it's better to ignore this interrupted error.
Fixes: #779
Signed-off-by: fupan.lfp <fupan.lfp@antfin.com>
=> channel: fix the issue of epoll_wait interrupted by signal

Makefile
The logic of this Makefile is to use "-extldflags '-static'" if
STATIC is defined. On the other hand, LDFLAGS is the standard name.
So we should avoid using LDFLAGS to avoid build failure.
Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
=> Makefile: do not use LDFLAGS to avoid environment contamination

device.go, device_test.go, grpc.go
With this change, a container is not longer given access to
the underlying nvdimm root partition.
This is done by explicitly adding the nvdimm root partition
to the device cgroup of the container.
Fixes #791
=> device: Do not allow container access to the nvdimm rootfs

device.go, device_test.go, grpc.go
With this change, a container is not longer given access to
the underlying nvdimm root partition.
This is done by explicitly adding the nvdimm root partition
to the device cgroup of the container.
Fixes #791
(cherry picked from commit a88af321f7c591404b0316320c46591fa8250992)
=> backport: device: Do not allow container access to the nvdimm rootfs

device.go
For docker in docker scenario, the nested container created
has entry "b *:* m" in the list of devices it is allowed to access
under /sys/fs/cgroup/devices/docker/{ctrid}/devices.list.
This entry was causing issues while starting a nested container
as we were denying "m" access to the rootfs block devices.
With this change we add back "m" access, the container would be
allowed to create a device node for the rootfs device but will
not have read-write access to the created device node.
This fixes the docker in docker use case while still making sure
the container is not allowed read/write access to the rootfs.
Note, this could also be fixed by simply skipping {"Type : "b"}
while creating the device cgroup with libcontainer.
But this seems to be undocumented behaviour at this point,
hence …
=> device: Ease device access for rootfs device to allow node creation

device.go
For docker in docker scenario, the nested container created
has entry "b *:* m" in the list of devices it is allowed to access
under /sys/fs/cgroup/devices/docker/{ctrid}/devices.list.
This entry was causing issues while starting a nested container
as we were denying "m" access to the rootfs block devices.
With this change we add back "m" access, the container would be
allowed to create a device node for the rootfs device but will
not have read-write access to the created device node.
This fixes the docker in docker use case while still making sure
the container is not allowed read/write access to the rootfs.
Note, this could also be fixed by simply skipping {"Type : "b"}
while creating the device cgroup with libcontainer.
But this seems to be undocumented behaviour at this point,
hence …
=> Backport: device: Ease device access for rootfs device to allow node creation

grpc.go, oci.go, oci_test.go
OCI hooks fails to run since the code was writing the config.json
to the read-only path. This patch fixes it
Fixes: #2763
Signed-off-by: Pradipta Kumar bpradipt@in.ibm.com
=> oci: Fix running of OCI hooks

device.go
For docker in docker scenario, the nested container created
has entry "b *:* m" in the list of devices it is allowed to access
under /sys/fs/cgroup/devices/docker/{ctrid}/devices.list.
This entry was causing issues while starting a nested container
as we were denying "m" access to the rootfs block devices.
With this change we add back "m" access, the container would be
allowed to create a device node for the rootfs device but will
not have read-write access to the created device node.
This fixes the docker in docker use case while still making sure
the container is not allowed read/write access to the rootfs.
Note, this could also be fixed by simply skipping {"Type : "b"}
while creating the device cgroup with libcontainer.
But this seems to be undocumented behaviour at this point,
hence …
=> Backport:device: Ease device access for rootfs device to allow node creation

network.go
agent does not check if /etc/resolv.conf exists, if it does not exist,
setDns will fail and causes the container to fail to run. sometimes,we
don't need dns in guest vm, so it's better to skip and return nil if
/etc/resolv.conf does not exists.
Fixes: #829
Signed-off-by: Shukui Yang <keloyangsk@gmail.com>
=> network: Fix Could not create destination mount point: /etc/resolv.conf

device.go, device_test.go
The way the agent updates device and resource entries one by one for guest versus host information can lead to it incorrectly updating devices because of major:minor collisions, either between host and guest numbering (issue #834) or between block and character devices (issue #835).
This PR fixes both of them.
=> Fix potential major:minor conflicts during device updates

agent.go, device.go, device_amd64.go, device_arm64.go, device_ppc64le.go, device_s390x.go, device_test.go, mount_test.go
This is a fix for issue #848.  While we're there, simplify the code a bit and rename a poorly named data structure.
=> Consistent device address matching between `getDeviceName()` and `listenToUdevEvents()`

.ci/run.sh, .ci/run_arm64.sh
"make proto" will fail on arm64 using docker 18.06. This bug will be
gone if using docker 19.03. so upgrade docker before "make proto"
for arm64.
Fixes: #861
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>
@jodh-intel @devimc
=> ci: install docker 19.03 for arm64 to let build image go

agent.go, device.go, device_amd64.go, device_arm64.go, device_ppc64le.go, device_s390x.go, device_test.go, mount_test.go
Currently, rootBusPath is set as a constant value. Bus this pcie bus path
is not alway static, eg. the rootBus on arm64 is
"/devices/platform/4010000000.pcie/pci0000:00". The address part of
"4010000000.pcie" may vary with the maxMem in qemu so it should not be a
fixed value.
For exmaple:
HIGH PCIE address reserved in qemu on virt is from 0 to 512G. The lower
part of address may be allocated to normal memory. In general, normal memory
is largely less than 256G, so the base address of HIGH PCIE can be 256G.
But, in case the maxmem is large enough, like around 256G, the base address
of HIGH PCIE must be increase, eg. 300G.
In the current implementation of kata-runtime, the maxmem in qemu is the host
memory size. So if the host memory size is large enough, the prefix of the
pci device path …
=> rootBusPath: create rootBusPath dynamically.

agent.go, device_arm64.go
PCI bus path in qemu/arm64 is different between acpi enabled and
disabled. It's better to check if there is a pci bus path for acpi which
is a static value before try to offer a varying pci bus path for no acpi.
Fixes: #881
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>
@jodh-intel @devimc
=> arm/pci: add create pci bus path support for acpi
