kata-containers/agent

.pullapprove.yml
Have the agent team approve PRs.
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>
=> pullapprove: Initial commit

protocols/client/client.go, protocols/client/client_test.go, protocols/mockserver/mockserver.go
It's indeed kata-containers...
=> fix import path

CODE_OF_CONDUCT.md
We follow the OpenStack Foundation CoC.
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>
=> CoC: Add Code Of Conduct

protocols/client/client.go, protocols/mockserver/mockserver.go
1. dial with blocking
2. test addr scheme correctly
3. fix mock server startcontainer check
=> fix client unix dialer and mock server

mount.go
mount: Handle storage options as flags and options combination
The Options field inside Storage structure is used to pass both
flags and data to the mount() system call. The semantic behind
this actually checks if an option from the list matches with a
flag from a specific list of flags. In case it does not match
any flag, the option is considered as a real option that should
be used as data parameter.
Fixes #26
=> mount: Handle storage options as flags and options combination

.gitignore, Makefile, kata-agent.service.in, kata-containers.target
Install target will install systemd units if INIT makefile variable is "no".
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>
=> makefile: Add install target

Dockerfile, Makefile, protocols/grpc/oci.pb.go
Add Dockerfile for agent, now we support updating grpc protocols with a
docker container.
Signed-off-by: Zhang Wei <zhangwei555@huawei.com>
=> Add Dockerfile

protocols/mockserver/mockserver.go
status.Errorf can set codes to error.  Then the function can run some special
error handler with the error.
Signed-off-by: Hui Zhu <teawater@hyper.sh>
=> mockserver.go: replace fmt.Errorf and errors to status

.travis.yml, README.md
* Add codecov and Travis badges
* Report code coverage back to codecov
=> Add README badges and report code coverage

.pullapprove.yml
Signed-off-by: Lai Jiangshan <jiangshanlai@gmail.com>
=> add rfc as a pending state

grpc.go, hack/update-generated-agent-proto.sh, protocols/grpc/agent.pb.go, protocols/grpc/health.pb.go, protocols/grpc/healthpb_test.go, protocols/grpc/oci.pb.go, protocols/grpc/ocipb_test.go, protocols/mockserver/mockserver.go
use gogo protobuf types and gogofast to generate grpc code.
fixes #37 
ref: https://github.com/gogo/protobuf/issues/325
=> use gogo protobuf types and gogofast to generate grpc code

.ci/setup.sh, .travis.yml
Require all PRs to contain a "Fixes #XXX" comment and a
"Signed-off-by:" comment.
Fixes #76.
=> CI: Enable checkcommits

codecov.yml
codecov: Add codecov.yml
This commit introduces a codecov.yml file to be able to specify
some files/directories we don't want to cover.
Fixes #84
=> codecov: Add codecov.yml

agent.go
When agent is configured as init, run init setup first before doing
anything else.
Fixes: #141
=> agent: run init setup first

network.go
-Handle error case and return error from the function getInterface.
-Removed goto usage and replaced with defer func() handling within
updateInterface function.
-Added comment describing the updateInterface function
-validate iface parameter before nethandle to avoid unnecessary work
if we have an error
Fixes #151
Signed-off-by: Eric Ernst <eric.ernst@intel.com>
=> network: handle error case in getInterface/updateInterface

device.go, device_test.go
Add a log call showing device details and then validate what
parts of the device can be checked.
Fixes #172.
=> device: Add validation and debug

agent.go
Add a function that announces agent capabilities (version, device and storage drivers and total guest kernel memory).
=> Add announce log call

grpc.go
In case the container creation fails, we need a proper rollback
regarding the mounts previously performed.
Fixes #195
=> agent: Rollback properly when container creation fails

grpc.go
The rollback does not work as expected because the error has to be
checked from the defer itself.
Fixes #205
=> agent: Fix container creation rollback

protocols/client/client.go, protocols/client/client_test.go
When enableYamux is set, dial the grpc server with builtin yamux
translation support.
Fixes: #200
=> protocol: client: enable builtin yamux client support

channel.go
syscall.EpollWait() gives ENOSYS: function not implemented error
(from Linux kernel), thus because epoll_wait is deprecated, and
only the newer epoll_pwait is provided on Linux/arm64. Golang has
fixed this issue(https://github.com/golang/go/issues/10235).
However, the implementation exits in x/sys/unix, not in the
standard Go syscall package.
Fixes: #240
Signed-off-by: Penny Zheng <penny.zheng@arm.com>
Signed-off-by: Wei Chen <wei.chen@arm.com>
=> channel: Support Epoll on Arm64

agent.go
Convert all non-string types into strings prior to logging to avoid
attempting to display non-string types with the `%q` format verb.
Fixes #270.
=> logging: Fix handling of non-string fields when PID 1

.travis.yml
Fixes: #276
Signed-off-by: Nitesh Konkar niteshkonkar@in.ibm.com
=> travis: Enable travis ci for ppc64le

grpc.go
The runtime should clear the PID namespace from the config
before sending it to the agent. Add a check in the agent to make
sure PID namespace is not recieved in the configuration.
Information about PID namespace is conveyed by means of a flag instead.
Fixes #285
=> namespace: Add check to make sure PID namespace is not received

protocols/client/client.go
For yamux builtin client, we should close the yamux session when closing
the stream otherwise the session keeps open and can confuse the server.
=> protocols/client: close yamux session when closing the stream

Dockerfile
Fixes #335
Signed-off-by: Zichang Lin <linzichang@huawei.com>
=> build: fix make proto error

.travis.yml
travis: Add variable needed to run static checks
travis: bump golang version to 1.10.x
=> travis: Add variable needed to run static checks and bump golang version

agent.go, grpc.go, grpc_test.go, reaper.go
There will be multiple waitProcess() requests
issued before process exits, and all those requests
should be fulfilled.
Fixes: #129
Fixes: #333
Signed-off-by: fupan lifupan@gmail.com
=> Multi wait process

agent.go
Kata agent does not wait for memory hotplug, and kata-runtime
does not wait on cpu/memory online. As a temporary fix, let's
make sure memory are onlined by the uevent listener at least.
Fixes: #363
=> agent: auto-online hotplug memory

grpc.go, grpc_test.go
/sys/devices/system/memory/block_size_bytes will not exist when guestos
doesn't support memory hotplug. Add judgement when file
/sys/devices/system/memory/block_size_bytes doesn't exist.
Fixes #394
Signed-off-by: Clare Chen <clare.chenhui@huawei.com>
=> agent: judge whether /sys/devices/system/memory/block_size_bytes exist.

network.go, network_test.go
In case of ipvlan plugin, the default route has an empty gateway.
Set this to default gateway value before adding this route with
netlink.
Fixes #403
=> network: Handle default route where gateway is empty

kata-agent.service.in, kata-containers.target
Systemd files has not license header, this properly add it.
Fixes: #531
=> license: add license header

mount.go
We need a proper rollback to decrement the sandbox storage
reference counter when addStorages() failed.
Fixes: #549
Signed-off-by: Xie Yongji <xieyongji@baidu.com>
(cherry picked from commit c66349b6c91156fbf59027e6c57f6aa211f365d0)
Signed-off-by: Ganesh Maharaj Mahalingam <ganesh.mahalingam@intel.com>
=> mount: Add a proper rollback path to addStorages()

grpc_test.go
Unit test for `onlineResources` function.
fixes #387
=> grpc: add unit test for onlineResources function

documentation/features/cpuset.md
Correct a spelling mistake.
Fixes: #576.
=> docs: Fix spelling

agent.go
Child subreaper is a thread local property. We need to lock os
thread to make sure the underlying go runtime M thread is not
scheduled off and then quits. Otherwise it is possible that we
lose the subreaper M thread and fail to wait child threads.
Fixes: #582
=> agent: lock subreaper agent thread

agent.go, agent_test.go, config_test.go, device.go, device_test.go, grpc.go, grpc_test.go, mount.go, mount_test.go
Added lots of new unit tests. This required a number of changes to the main code as documented in individual commits.
Fixes: #561.
=> Improve unit test coverage

.ci/install_go.sh, .travis.yml
Install the golang version specified in the versions.yaml
fixes #633
=> travis: Fix golang version

network.go, network_test.go
Sandbox has network but not dns. Set
dns in the sandbox.
Fixes: #589
Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>
=> network: Setup DNS for sandbox

agent.go, config.go, protocols/client/client.go, protocols/client/client_test.go
=> firecracker: send logs to a vsock port

cgroup.go
Fixes: #693
Signed-off-by: choury <chouryzhou@tencent.com>
=> agent: get current cpuset from /sys/devices/system/cpu/online

grpc.go, grpc_test.go
Don't use the /sys/devices/system/memory/probe interface on architectures
where the firmware (ACPI) is notifying the system of hotplugged memory.
This fixes an issue with the agent erroring out when the guest-kernel is
compiled with CONFIG_ARCH_MEMORY_PROBE=y.
Fixes: #712
Signed-off-by: Ralf Haferkamp <rhafer@suse.com>
=> Fix mem-hotplug on x86 when ARCH_MEMORY_PROBE is set

protocols/client/client.go
When the client tries to connect sometimes a race condition
could happen when the between bind and listen calls in the agent
vsock side.
This will block the hypervisor wanting for a response and
as consequence the agent client where it checks for an OK
response.
This case needs to be handled by the guest kernel, see
https://lore.kernel.org/netdev/668b0eda8823564cd604b1663dc53fbaece0cd4e.camel@intel.com/
As an extra protection make the agent client timeout if no OK response
is given. The response should be quick so is OK to wait a few seconds
and then timeout.
This also allow to return an error from the dialler function so retry
does not fallback on grpc retry making retries faster.
Fixes: #372
=> protocols: client: Add timeout for hybrid vsock handshake

agent.go
Delete `uEv.DevPath` from pciDeviceMap when recieving `remove` uevent.
Fixes #729
Signed-off-by: Li Yuxuan <liyuxuan04@baidu.com>
=> agent: Remove dev from pciDeviceMap when device is unplugged

grpc.go
fix #832 
cpusetGuest should be newCpuset in log
=> fix typo in grpc.go
